"""Canonical skill names mapped to the aliases that refer to them."""

SKILLS: dict[str, set[str]] = {
    "python": {"python", "python3"},
    "java": {"java"},
    "javascript": {"javascript", "js"},
    "typescript": {"typescript", "ts"},
    "c#": {"c#", "csharp"},
    "c++": {"c++", "cpp"},
    "sql": {"sql", "t-sql", "pl/sql"},
    "html": {"html", "html5"},
    "css": {"css", "css3"},
    "react": {"react", "react.js", "reactjs"},
    "angular": {"angular", "angularjs"},
    "node.js": {"node.js", "nodejs", "node"},
    "fastapi": {"fastapi"},
    "django": {"django"},
    "flask": {"flask"},
    ".net": {".net", "dotnet", "asp.net"},
    "rest api": {"rest api", "rest apis", "restful api", "restful apis", "web services"},
    "microservices": {"microservice", "microservices"},
    "postgresql": {"postgresql", "postgres"},
    "mysql": {"mysql"},
    "sql server": {"sql server", "mssql"},
    "oracle": {"oracle"},
    "mongodb": {"mongodb", "mongo"},
    "aws": {"aws", "amazon web services"},
    "azure": {"azure", "microsoft azure"},
    "gcp": {"gcp", "google cloud"},
    "docker": {"docker"},
    "kubernetes": {"kubernetes", "k8s"},
    "ci/cd": {"ci/cd", "cicd", "continuous integration", "continuous delivery"},
    "jenkins": {"jenkins"},
    "git": {"git", "github", "gitlab", "bitbucket"},
    "linux": {"linux", "unix"},
    "agile": {"agile", "scrum", "kanban"},
    "jira": {"jira"},
    "unit testing": {"unit test", "unit tests", "unit testing"},
    "integration testing": {"integration test", "integration tests", "integration testing"},
    "selenium": {"selenium"},
    "katalon": {"katalon"},
    "groovy": {"groovy"},
    "sonarqube": {"sonarqube"},
    "pytest": {"pytest"},
    "code review": {"code review", "code reviews"},
    "database design": {"database design", "data modelling", "data modeling", "erd"},
    "data migration": {"data migration"},
    "etl": {"etl"},
    "power bi": {"power bi", "powerbi"},
    "machine learning": {"machine learning", "ml"},
    "llm": {"llm", "llms", "large language model", "large language models"},
    "prompt engineering": {"prompt engineering"},
    "outsystems": {"outsystems"},
    "payment gateway": {"payment gateway", "payment gateways", "payment integration"},
    "oauth": {"oauth", "oauth2", "openid connect"},
    "jwt": {"jwt", "json web token"},
    "openapi": {"openapi", "swagger"},
}

# Reverse lookup so a matched alias resolves back to its canonical name.
ALIAS_TO_SKILL: dict[str, str] = {
    alias: canonical for canonical, aliases in SKILLS.items() for alias in aliases
}


